version: 2
jobs:

  php70:
    docker:
      - image: circleci/php:7.0
    working_directory: ~/site
    steps:
      - run: php --version
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit -c phpunit.xml.dist
      - run: ./vendor/bin/php-cs-fixer --dry-run -v fix

workflows:
  version: 2
  test:
    jobs:
      - php70
